---
title: "Two strain model output post-processing"
author: "James Azam"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    keep_md: yes
    toc: yes
---

```{r echo=FALSE, include=FALSE}
#' load packages
library('tidyverse')
library('ggthemes')
library('mdthemes')
library('scales')
library('forcats')
library('stringr')
library('bib2df')
library('conflicted')
library('Hmisc')

#resolve package function conflicts
conflict_prefer('filter', 'dplyr')
conflict_prefer('select', 'dplyr')
conflict_prefer('kable', 'knitr')
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dev = 'jpeg')
knitr::opts_chunk$set(fig.width = 8, fig.height = 6)
knitr::opts_chunk$set(message = FALSE)
```

```{r}

#helper scripts
source('./sim_config_global_params.R')

#Load the model output
case_studies_dynamics_df <- readRDS('../../model_output/dynamics_case_studies_controlled_vs_uncontrolled.rds')
#Rescale the population proportions to total sizes
case_studies_dynamics_rescaled <- case_studies_dynamics_df %>%
    group_by(variant_emergence_day, npi_intensity, vax_speed) %>% 
    mutate(incidence = Iw + Iwm + Im + Imw, 
           outbreak_size = max(K), #what is the outbreak size for each emergence day and when does it occur
           peak_time = which.max(incidence)
           ) %>% 
    mutate(across(.cols = c(incidence, outbreak_size), .fns = ~ .x*target_pop)) %>%  
    select(!starts_with(c('S', 'R', 'V', 'K'), ignore.case = FALSE)) %>% 
    ungroup()



#Add a column to label the control scenarios
case_studies_dynamics <- case_studies_dynamics_rescaled %>% 
    mutate(control_type = case_when(npi_intensity == 0 & vax_speed > 0 ~ 'vax_only', 
                                    npi_intensity > 0 ~ 'vax+npi',
                                    npi_intensity == 0 & vax_speed == 0 ~ 'no_control'
                                    ),
           control_type = as.factor(control_type)
           )


#Summarise the results
outbreak_summaries <- case_studies_dynamics %>% 
    group_by(variant_emergence_day, npi_intensity, vax_coverage, vax_speed) %>% 
    summarise(control_type = unique(control_type), 
              peak_incidence = max(incidence),
              outbreak_size = max(outbreak_size), 
              .groups = 'drop'
              ) %>% 
    # filter(vax_coverage == 0.0) %>% 
    arrange(outbreak_size)


#function to calculate percent change
calc_percent_change <- function(original, new){
    p_change <- ((original-new)/original)*100
    return(p_change)
}

```

#Summaries

# Unmitigated outbreak

```{r}

no_control_outbreak_summaries <- outbreak_summaries %>% 
    filter(control_type == 'no_control') %>% 
    select(c(variant_emergence_day, peak_incidence, outbreak_size)) %>% 
    arrange(peak_incidence)

knitr::kable(no_control_outbreak_summaries)
```


# Vax only

```{r}

vax_only_impact <- outbreak_summaries %>% 
    filter(control_type == 'vax_only') %>% 
    arrange(peak_incidence)

knitr::kable(vax_only_impact)
```


# Vax + NPIs 

```{r}

vax_and_npi_impact <- outbreak_summaries %>% 
    filter(control_type == 'vax+npi') %>%
    arrange(peak_incidence)

knitr::kable(vax_and_npi_impact)
```